variables:
  CONAN_USERNAME: "bincrafters"
  CONAN_REFERENCE: "Azure-C-Shared-Utility/1.0.46"
  CONAN_CHANNEL: "ci"

.conan-run: &conan-run
  before_script:
    - sudo pip install -U conan --upgrade
    - sudo pip install -U conan_package_tools
    - conan user
  script:
    - python build.py

gcc-4.9:
  image: lasote/conangcc49
  variables:
    CONAN_GCC_VERSIONS: "4.9"
  <<: *conan-run

gcc-5.4:
  image: lasote/conangcc54
  variables:
    CONAN_GCC_VERSIONS: "5.4"
  <<: *conan-run

gcc-6.3:
  image: lasote/conangcc63
  variables:
    CONAN_GCC_VERSIONS: "6.3"
  <<: *conan-run

clang-3.9:
  image: lasote/conanclang39
  variables:
    CONAN_CLANG_VERSIONS: "3.9"
  <<: *conan-run

clang-4.0:
  image: lasote/conanclang40
  variables:
    CONAN_CLANG_VERSIONS: "4.0"
  <<: *conan-run
